config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  resources :messages
  resources :sessions, as: :sets

  resources :pages do
    collection do
      get :about
    end
  end
  root 'pages#home'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'chatroom/index'
  # mount ActionCable.server, at: '/cable'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # dung de phan trang
    @articles = Article.paginate(page: params[:page], per_page: 3)
    # @articles = Article.all
  end

  def show
    # use before action.
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
      flash[:notice] = 'Successfully Saved Article'
    else
      render 'new'
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Successfully Updated Article'
      redirect_to article_path(@article)
    else
      render 'edit'
    end

  end

  def destroy

    Article.find(params[:id]).destroy
    # redirect_to :action => 'index'
    flash[:notice] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def get_article
    @article = Article.find(params[:id])
  end

  def article_params
    # muốn nhận được nhiều category cho 1 article thì để biến nhận vào là 1 mảng [].
    # và chứa nhiều id của đối tượng đấy
    # hoặc chứa 1 id (bên view cũng khai báo id của đối tượng category nằm trong đối tượng article)
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if !logged_in? || (current_user != @article.user && !current_user.admin?)
      flash[:danger] = "Only can delete or edit your article"
      redirect_to
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= link_to "Create new article", new_article_path %>

<% obj.each do |a| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">

        <div class="article-title">
          <%= link_to a.title, article_path(a) %>

        </div>
        <div class="article-body">
          <%= truncate(a.description, length: 100) %>
          <small>Created by: <%= a.user.username %>, <%= time_ago_in_words(a.created_at) %>ago
            last updated:<%= time_ago_in_words(a.updated_at) %> </small>
        </div>
        <% if a.categories.any? %>
          <p>Categories: <%= render 'categories/category', categories: a.categories %></p>
        <% end %>

        <% if logged_in? && (current_user.id == a.user.id || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit", edit_article_path(a), class: "btn btn-xs btn-primary" %>
            <%= button_to "Delete", article_path(a), :method => "delete", data: { confirm: "Are you sure" },
                          class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |msg| %>
    <ul>
      <li> <%= msg %></li>
    </ul>
  <% end %>
<% end %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: :Title, autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %><br>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description ", autofocus: true %>

        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
<!--            them tuy chon nhieu checkbox cho articles-->
            <%= f.collection_check_boxes  :category_ids, Category.all, :id, :name do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>

          </div>
        </div>

      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 ">
          <%= f.submit(@article.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>

    <% end %>
    <div class="col-xs-4 col-xs-offset-4 ">
      <%= link_to "Back to list", articles_path %>

    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%=render 'form' %>

<%# if @article.errors.any? %>
  <%# @article.errors.full_messages.each do |msg| %>
<!--    <ul>-->
<!--      <li> <%#= msg %></li>-->
<!--    </ul>-->
  <%# end %>
<%# end %>
<%#= form_for @article do |f|%>

<!--  <p>-->
<!--    <%#= f.label :title %><br>-->
    <%#= f.text_field :title %>
<!--  </p>-->
<!--  <p>-->
<!--    <%#= f.label :description %><br>-->
    <%#= f.text_area :description %>
<!--  </p>-->
<!--  <p>-->
    <%#= f.submit "Update" %>
<!--  </p>-->
<%# end %>

<%#= link_to "Back to list", articles_path %>

app/views/articles/index.html.erb
<h1 align="center">Article List</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>


<%#= link_to "Create new article", new_article_path %>

<%# @articles.each do |a| %>
<!--  <div class="row">-->
<!--    <div class="col-xs-8 col-xs-offset-2">-->
<!--      <div class="well well-lg">-->

<!--        <div class="article-title">-->
<%#= link_to a.title, article_path(a) %>

<!--        </div>-->
<!--        <div class="article-body">-->
<%#= truncate(a.description, length: 100) %>
<!--          <small>Created by: <%#= a.user.username %>, <%#= time_ago_in_words(a.created_at) %>ago-->
<!--            last updated:<%#= time_ago_in_words(a.updated_at) %> </small>-->
<!--        </div>-->
<!--        <div class="article-actions">-->
<%#= link_to "Edit", edit_article_path(a), class: "btn btn-xs btn-primary" %>
<%#= button_to "Delete", article_path(a), :method => "delete", data: { confirm: "Are you sure" },class: "btn btn-xs btn-danger" %>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->

<%# end %>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%=render 'form' %>


<%# if @article.errors.any? %>
  <%# @article.errors.full_messages.each do |msg| %>
<!--    <ul>-->
<!--      <li> <%#= msg %></li>-->
<!--    </ul>-->
  <%# end %>
  <%# end %>


<%#= form_for @article do |f|%>

<!--  <p>-->
<!--    <%#= f.label :title %><br>-->
    <%#= f.text_field :title %>
<!--  </p>-->
<!--  <p>-->
<!--    <%#= f.label :description %><br>-->
    <%#= f.text_area :description %>
<!--  </p>-->
<!--  <p>-->
    <%#= f.submit "Create" %>
<!--  </p>-->
<%# end %>


<%#= link_to "Back to list", articles_path %>

app/views/articles/show.html.erb
<h1>Show Article</h1>

<p>
  Title: <%= @article.title %>
</p>
<ul class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
      <li class="article-title">
        <%= link_to @article.user.username, user_path(@article.user) %>
      </li>
      <li><small>
        <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
      </small></li>
    </div>
  </div>
</ul>
<p>Description: <%= @article.description %></p>

<% if @article.categories.any? %>
  <p>Categories: <%= render 'categories/category' , categories: @article.categories %></p>
<% end %>
<% if logged_in? && (current_user.id == @article.user.id || current_user.admin?) %>

  <%= link_to "Edit", edit_article_path(@article) %> |
  <%= button_to "Delete", article_path(@article), method: :delete %> |
<% end %>
<%= link_to "Back to list", articles_path %>