config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  resources :messages
  resources :sessions, as: :sets

  resources :pages do
    collection do
      get :about
    end
  end
  root 'pages#home'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'chatroom/index'
  # mount ActionCable.server, at: '/cable'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_param)
    if @category.save
      flash[:success] = 'Category Create Successful'
      redirect_to categories_path
    else
      flash[:danger] = 'OP!!! Seem Somethings Went Wrong'
      render new_category_path
    end

  end

  def show
    @category = Category.find(params[:id])
    @articles_by_category = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_param
    params.require(:category).permit(:name)

  end

  public def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = 'You are not admin!!!'
      redirect_to categories_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% categories.each do |category| %>
  <span class="badge"><%= link_to category.name, category_path(category) %>&nbsp;</span>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<div align="center">
  <%= will_paginate @categories %>
</div>
<% @categories.each do |c| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">

        <div class="article-title">
          <%= link_to c.name, category_path(c) %>

        </div>
        <div class="article-body">
          <small>Created at: <%= time_ago_in_words(c.created_at) %>ago
            last updated:<%= time_ago_in_words(c.updated_at) %> </small>
        </div>

      </div>
    </div>
  </div>

<% end %>
<div align="center">
  <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1>Category</h1>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |msg| %>
    <ul>
      <li> <%= msg %></li>
    </ul>
  <% end %>
<% end %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@category, :html => { class: "form-horizontal", role: "form" }) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter name", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 ">
          <!--          thay doi Create or Create in-->
          <%= f.submit(@category.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>

    <% end %>
    <div class="col-xs-4 col-xs-offset-4 ">
      <%= link_to "Back to list", articles_path %>

    </div>


  </div>
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>


<h4 align="center"><%= @category.name %>'s articles</h4>


<!--truyen du lieu vao cho 1 component-->
<div align="center">
  <%= will_paginate @articles_by_category %>
</div>
<%= render 'articles/article', obj: @articles_by_category %>

<div align="center">
  <%= will_paginate @articles_by_category %>
</div>