config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  resources :messages
  resources :sessions, as: :sets

  resources :pages do
    collection do
      get :about
    end
  end
  root 'pages#home'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'chatroom/index'
  # mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates_uniqueness_of :name
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  mount_uploader :attachment, AttachmentUploader
  validates :body, presence: true

  scope :custom_display, -> { order(:created_at).last(10) }
end

app/models/user.rb
class User < ApplicationRecord
  #tao bang quan he
  has_many :articles,
           dependent: :destroy #dòng này dùng để bảo rails xóa hết những bài blog của user này
  #downcase for email anytime user create an account
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            length: { maximum: 105 },
            uniqueness: true,
            format: { with: VALID_EMAIL_REGEX }
  #khai bao de su dung password secure (password_digest)
  has_secure_password
  has_many :messages


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # dung de phan trang
    @articles = Article.paginate(page: params[:page], per_page: 3)
    # @articles = Article.all
  end

  def show
    # use before action.
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
      flash[:notice] = 'Successfully Saved Article'
    else
      render 'new'
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Successfully Updated Article'
      redirect_to article_path(@article)
    else
      render 'edit'
    end

  end

  def destroy

    Article.find(params[:id]).destroy
    # redirect_to :action => 'index'
    flash[:notice] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def get_article
    @article = Article.find(params[:id])
  end

  def article_params
    # muốn nhận được nhiều category cho 1 article thì để biến nhận vào là 1 mảng [].
    # và chứa nhiều id của đối tượng đấy
    # hoặc chứa 1 id (bên view cũng khai báo id của đối tượng category nằm trong đối tượng article)
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if !logged_in? || (current_user != @article.user && !current_user.admin?)
      flash[:danger] = "Only can delete or edit your article"
      redirect_to
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  def index
    @message = Message.new
    @messages = Message.all.custom_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  skip_before_action :verify_authenticity_token

  def create
    # add  message for current user
    message = current_user.messages.build(message_params)
    if message.save
      # de gui du lieu qua socket
      ActionCable.server.broadcast 'chatroom_channel',
                                   mod_message: message_render([message]), message: message
    else

      flash[:danger] = 'message can not be empty'
      redirect_to chatroom_index_path
    end
  end

  def destroy
    Message.find(params[:id]).destroy
    flash[:notice] = 'Message was successfully deleted'
    redirect_to chatroom_index_path


  end

  def message_params
    params.require(:message).permit(:body, :attachment)
  end

  private

  def message_render(message)
    # render(partial: 'message', message: message)
    render_to_string(partial: 'message', locals: { messages: message })
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #nhan doi tuong truyen vao tu view co ten la session
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "login success"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "email or password not correct!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "logout success"
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_same_user, only: [:edit, :update]

  def index
    #phan trang
    @users = User.all.paginate(page: params[:page], per_page: 3)
    # @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "wellcome to the blog"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    require_user
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Update information successful'
      redirect_to articles_path
    else
      render 'edit'
    end
    # if
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User and their article was successfully deleted'
    redirect_to users_path

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    @user = User.find(params[:id])
    if !logged_in? || current_user != @user
      flash[:danger] = 'your request was denied'
      redirect_to articles_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->

  <!-- Section: Social media -->

  <!-- Section: Links  -->

  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Learning Ruby </a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: lightsteelblue">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Article", new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "new Category", new_category_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Chat Room", chatroom_index_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "View profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_path(current_user), class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
          <li><%= link_to "Login", login_path, class: "nav-link" %></li>
        <% end %>

        <!--        <li class="nav-item">-->
        <!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
        <!--        </li>-->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |name, msg|  %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navigation' %>
<div class="container">
  <%= render 'layouts/notice' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<!--to debug and show to display-->
<%#= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="center jumbotron" style="text-align: center">

<h1>YOUR BLOG</h1>

<%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg btn-xlarge " %>
</div>